# Generated by Django 2.2 on 2019-05-27 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20190413_2105'),
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='agency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='agency.Agency'),
            preserve_default=False,
        ),
    ]
