# Generated by Django 2.2 on 2019-05-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_destination_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.TextField(),
        ),
    ]
