# Generated by Django 2.2 on 2019-05-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0005_auto_20190527_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(default='/media/images/default', upload_to=''),
            preserve_default=False,
        ),
    ]
