# Generated by Django 2.2 on 2019-05-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0006_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
