# Generated by Django 2.2 on 2019-05-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0007_auto_20190527_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
