# Generated by Django 2.2 on 2019-05-27 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0008_auto_20190527_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='start_date',
        ),
    ]
