# Generated by Django 2.2 on 2019-05-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0010_auto_20190527_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
