# Generated by Django 2.2 on 2019-05-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0012_auto_20190527_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
