# Generated by Django 2.2 on 2019-05-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0014_auto_20190530_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.TextField(),
        ),
    ]
