# Generated by Django 2.2 on 2019-05-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0016_auto_20190530_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='selector_url',
            field=models.CharField(default='nista', max_length=50),
            preserve_default=False,
        ),
    ]
