# Generated by Django 2.2 on 2019-06-01 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0017_destination_selector_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyoffer',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='dailyoffer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='DailyOffer',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
