# Generated by Django 2.2 on 2019-06-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0019_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
