# Generated by Django 2.2 on 2019-04-13 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_remove_agency_selector'),
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selector',
            name='agency',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='agency.Agency'),
            preserve_default=False,
        ),
    ]
