# Generated by Django 2.2 on 2019-05-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_selector_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selector',
            name='description',
        ),
        migrations.RemoveField(
            model_name='selector',
            name='location',
        ),
        migrations.RemoveField(
            model_name='selector',
            name='price_excludes',
        ),
        migrations.RemoveField(
            model_name='selector',
            name='price_includes',
        ),
        migrations.AddField(
            model_name='selector',
            name='num_of_nights',
            field=models.CharField(default='nista', max_length=100),
            preserve_default=False,
        ),
    ]
