# Generated by Django 2.2 on 2019-05-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_auto_20190527_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selector',
            name='travel_plan',
            field=models.CharField(max_length=100),
        ),
    ]
