# Generated by Django 2.2 on 2019-05-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0005_auto_20190527_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='selector',
            name='destination_url',
            field=models.CharField(default='a.putovanje', max_length=100),
            preserve_default=False,
        ),
    ]
