# Generated by Django 2.2 on 2019-05-31 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0006_selector_destination_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selector',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Agency'),
        ),
    ]
