# Generated by Django 2.2 on 2019-06-09 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0007_auto_20190531_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selector',
            name='image_gallery',
        ),
    ]
