# Generated by Django 2.2 on 2019-04-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_remove_agency_selector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
